DROP TRIGGER IF EXISTS before_delete_on_objects_delete_slices;
DROP TRIGGER IF EXISTS before_delete_on_multipart_uploads_delete_multipart_parts;
DROP TRIGGER IF EXISTS before_delete_on_multipart_parts_delete_slices;
DROP TRIGGER IF EXISTS after_delete_on_slices_delete_slabs;
