name: Sync OpenAPI Versions

permissions:
  contents: write
  pull-requests: write

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  sync:
    uses: SiaFoundation/workflows/.github/workflows/sync-openapi-version.yml@4495be4e01530009c7706c7c6fa9ac1031e12789 # master
    with:
      spec_path: openapi.yml
