name: Sync OpenAPI Versions

permissions:
  contents: write
  pull-requests: write

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  sync:
    uses: SiaFoundation/workflows/.github/workflows/sync-openapi-version.yml@2dc0b0ff59df8c1a5345719e34e62a398f7a165c # master
    with:
      spec_path: openapi.yml
