name: Sync OpenAPI Versions

permissions:
  contents: write
  pull-requests: write

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  sync:
    uses: SiaFoundation/workflows/.github/workflows/sync-openapi-version.yml@b42741de5798fcb1881143d714a923501ec4ff89 # v0.1.1
    with:
      spec_path: openapi.yml
