name: Add issues and PRs to Sia project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    uses: SiaFoundation/workflows/.github/workflows/project-add.yml@b42741de5798fcb1881143d714a923501ec4ff89 # master
    secrets: inherit
