name: Add issues and PRs to Sia project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    uses: SiaFoundation/workflows/.github/workflows/project-add.yml@4495be4e01530009c7706c7c6fa9ac1031e12789 # master
    secrets: inherit
