name: Update UI and open PR

on:
  repository_dispatch:
    types: [update-ui]
  # Enable manual trigger
  workflow_dispatch:

jobs:
  update-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Update UI and open PR
        uses: SiaFoundation/workflows/.github/actions/ui-update@22e56c0750c0febb09784caa01c60021e0b5f111 # master
        with:
          moduleName: 'renterd'
          goVersion: '1.21'
          token: ${{ secrets.GITHUB_TOKEN }}
